# Database properties
spring.datasource.url=jdbc:postgresql://localhost:5433/connect
spring.datasource.username=postgres
spring.datasource.password=Pragyaisha@100
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB